var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/models/generate-dressed/route.js")
R.c("server/chunks/[root-of-the-server]__1ba526c7._.js")
R.c("server/chunks/[root-of-the-server]__0e3367bd._.js")
R.c("server/chunks/node_modules_next_bb00e6a1._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_7e8f41ca._.js")
R.c("server/chunks/node_modules_@google-cloud_firestore_build_src_a55966bf._.js")
R.c("server/chunks/node_modules_@google-cloud_firestore_build_protos_0dc0789e._.js")
R.c("server/chunks/node_modules_@google-cloud_firestore_package_json_6c8d5984._.js")
R.c("server/chunks/node_modules_protobufjs_c594357a._.js")
R.c("server/chunks/node_modules_google-gax_fb0deaea._.js")
R.c("server/chunks/node_modules_c066c9e9._.js")
R.c("server/chunks/node_modules_@grpc_grpc-js_4855aa55._.js")
R.c("server/chunks/node_modules_tr46_3e4df63f._.js")
R.c("server/chunks/node_modules_@google-cloud_storage_60bc856c._.js")
R.c("server/chunks/node_modules_fefd8cdd._.js")
R.c("server/chunks/[externals]_sharp_6b522068._.js")
R.c("server/chunks/_next-internal_server_app_api_models_generate-dressed_route_actions_ad1d7db6.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/models/generate-dressed/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/models/generate-dressed/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
