'use client';

import React, { useState, useEffect, useRef } from 'react';
import { useParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import Shell from '@/components/Shell';
import { useSession } from 'next-auth/react';

interface CelebrityCheckData {
  timestamp?: string | { _seconds: number; _nanoseconds: number };
  status: 'pass' | 'review' | 'blocked' | 'error';
  facesDetected?: number;
  topMatch?: string | null;
  topScore?: number;
  flaggedMatches?: Array<{ name: string; score: number }>;
  modelVersion?: string;
  databaseVersion?: string;
  thresholds?: { review: number; block: number };
  durationMs?: number;
  note?: string;
  error?: string;
}

interface ModelData {
  id: string;
  modelId: string;
  name: string;
  description: string;
  gender: 'male' | 'female';
  referenceImageUrl?: string;
  cardImageUrl?: string;
  backReferenceImageUrl?: string;
  active: boolean;
  createdAt?: string;
  celebrityCheck?: CelebrityCheckData;
  // 4K model assets (generated by scripts/generate-model-assets.ts):
  // 4 high-res model references at 1:1 square 4K — full body F+B + legs F+B
  // — used as canonical reference set + as anchors for the M01/M02 pipeline.
  assets4K_fullBodyFront?: string;
  assets4K_fullBodyBack?: string;
  assets4K_legsFront?: string;
  assets4K_legsBack?: string;
  assets4K_updatedAt?: string;
}

export default function ModelDetailPage() {
  const params = useParams();
  const router = useRouter();
  const modelId = params?.id as string;
  const { data: session } = useSession();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const sessionAny = session as any;
  const user = session?.user
    ? { email: session.user.email || '', name: session.user.name || '', role: (sessionAny?.role as 'admin' | 'creator') || 'creator' }
    : { email: '', name: '', role: 'creator' as const };
  const isAdmin = user.role === 'admin';

  const [model, setModel] = useState<ModelData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  // Zoom state
  const [zoomMode, setZoomMode] = useState<'full' | 'head' | 'torso'>('full');
  const imgContainerRef = useRef<HTMLDivElement>(null);
  // 4K asset lightbox state — click an asset → opens lightbox (image fits
  // window). Click again → full 4K opens in a new browser tab.
  const [assetLightbox, setAssetLightbox] = useState<string | null>(null);
  useEffect(() => {
    if (!assetLightbox) return;
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setAssetLightbox(null);
    };
    window.addEventListener('keydown', handleKey);
    return () => window.removeEventListener('keydown', handleKey);
  }, [assetLightbox]);

  // Replace-reference-image upload path removed 2026-05-10. Generation +
  // Regenerate (overlay button on front image) is now the canonical flow.
  // To restore: re-add `uploading` state + `fileInputRef`, the `handleReplacePhoto`
  // handler below, and the JSX block that was at the bottom of the front column.

  // Delete state
  const [deleting, setDeleting] = useState(false);
  const [confirmDelete, setConfirmDelete] = useState(false);

  // Clone state
  const [cloning, setCloning] = useState(false);
  const [cloneId, setCloneId] = useState('');
  const [cloneName, setCloneName] = useState('');
  const [cloneDescription, setCloneDescription] = useState('');
  const [cloneGender, setCloneGender] = useState<'male' | 'female'>('female');
  const [showCloneForm, setShowCloneForm] = useState(false);

  // Back view generation state
  const [generatingBack, setGeneratingBack] = useState(false);
  // Front view regeneration state
  const [regeneratingFront, setRegeneratingFront] = useState(false);

  // Generate back view
  const handleGenerateBack = async () => {
    if (!model) return;
    setGeneratingBack(true);
    setError('');
    try {
      const res = await fetch('/api/models/generate-back', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ modelId: model.modelId || model.id }),
      });
      const data = await res.json();
      if (data.success && data.backUrl) {
        setModel({ ...model, backReferenceImageUrl: data.backUrl });
      } else {
        setError(data.error || 'Back view generation failed');
      }
    } catch {
      setError('Back view generation failed');
    } finally {
      setGeneratingBack(false);
    }
  };

  // Regenerate front reference — uses /api/models/generate-front, which
  // takes the existing front (or original upload) as identity anchor and
  // regenerates with the v2 styling (sports bra/bare torso + compression
  // shorts + infinity cove). Use case: a freshly-created model whose card
  // came out wrong (e.g. wrong styling, identity drift, distracting
  // background) — click to redo without deleting the model. The original
  // upload is preserved on the doc as `originalReferenceImageUrl`.
  const handleRegenerateFront = async () => {
    if (!model) return;
    setRegeneratingFront(true);
    setError('');
    try {
      const res = await fetch('/api/models/generate-front', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ modelId: model.modelId || model.id }),
      });
      const data = await res.json();
      if (data.success && data.frontUrl) {
        // Cache-bust the URL so the browser reloads the new image
        const cacheBusted = `${data.frontUrl}${data.frontUrl.includes('?') ? '&' : '?'}t=${Date.now()}`;
        setModel({ ...model, referenceImageUrl: cacheBusted });
      } else {
        setError(data.error || data.details || 'Front regeneration failed');
      }
    } catch {
      setError('Front regeneration failed');
    } finally {
      setRegeneratingFront(false);
    }
  };

  useEffect(() => {
    async function fetchModel() {
      try {
        const res = await fetch(`/api/models/${modelId}`);
        if (!res.ok) {
          if (res.status === 404) {
            setError('not_found');
          } else {
            setError('Failed to load model');
          }
          return;
        }
        const data = await res.json();
        setModel(data.model);
      } catch {
        setError('Connection error');
      } finally {
        setLoading(false);
      }
    }
    if (modelId) fetchModel();
  }, [modelId]);

  // handleReplacePhoto removed 2026-05-10 — see comment near uploading-state
  // declaration. /api/models/{id} PATCH still accepts a base64 dataUrl in
  // the referenceImageUrl field; the only thing removed was the UI surface.

  // Delete model
  const handleDelete = async () => {
    if (!model) return;
    setDeleting(true);
    try {
      const res = await fetch(`/api/models/${model.modelId || model.id}`, { method: 'DELETE' });
      const data = await res.json();
      if (data.success) {
        router.push('/models');
      } else {
        setError(data.error || 'Delete failed');
      }
    } catch {
      setError('Delete failed');
    } finally {
      setDeleting(false);
      setConfirmDelete(false);
    }
  };

  // Clone model
  const handleClone = async () => {
    if (!cloneId || !cloneName || !model) return;
    setCloning(true);
    setError('');
    try {
      const res = await fetch('/api/models', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          modelId: cloneId.toUpperCase(),
          name: cloneName,
          description: cloneDescription,
          gender: cloneGender,
          referenceImageUrl: model.referenceImageUrl || model.cardImageUrl,
          createdBy: user.email,
        }),
      });
      const data = await res.json();
      if (data.success) {
        router.push(`/models/${cloneId.toUpperCase()}`);
      } else {
        setError(data.error || 'Clone failed');
      }
    } catch {
      setError('Clone failed');
    } finally {
      setCloning(false);
    }
  };

  // Zoom styles for 9:16 full-body reference photos
  const zoomStyles: Record<string, React.CSSProperties> = {
    full: { objectFit: 'contain' as const, objectPosition: 'center', transform: 'scale(1)' },
    head: { objectFit: 'cover' as const, objectPosition: 'top center', transform: 'scale(2.5)', transformOrigin: '50% 6%' },
    torso: { objectFit: 'cover' as const, objectPosition: 'center', transform: 'scale(2)', transformOrigin: '50% 28%' },
  };

  if (loading) {
    return (
      <Shell user={user}>
        <div className="flex items-center justify-center py-20">
          <div className="w-6 h-6 border-2 border-neutral-300 border-t-neutral-900 rounded-full animate-spin" />
        </div>
      </Shell>
    );
  }

  if (error === 'not_found' || !model) {
    return (
      <Shell user={user}>
        <div className="text-center py-20">
          <p className="text-neutral-400 mb-3">Model not found</p>
          <Link href="/models" className="text-sm text-neutral-900 underline">Back to portfolio</Link>
        </div>
      </Shell>
    );
  }

  return (
    <Shell user={user}>
      <Link href="/models" className="text-sm text-neutral-500 hover:text-neutral-900 transition-colors mb-6 inline-block">
        &larr; Back to portfolio
      </Link>

      {/* Header — Fx + name + compact admin actions in the top-right corner */}
      <div className="flex items-start justify-between gap-6 mb-8">
        <div>
          <div className="flex items-baseline gap-3 mb-2">
            <h1 className="text-3xl font-bold text-neutral-900">{model.modelId}</h1>
            <span className="text-lg text-neutral-400">{model.name}</span>
          </div>
          <div className="flex items-center gap-2">
            <span className={`text-xs px-2 py-0.5 font-medium ${model.gender === 'female' ? 'bg-pink-50 text-pink-700' : 'bg-blue-50 text-blue-700'}`}>
              {model.gender === 'female' ? 'Woman' : 'Man'}
            </span>
            <span className={`text-xs px-2 py-0.5 font-medium ${model.active ? 'bg-green-50 text-green-700' : 'bg-neutral-100 text-neutral-500'}`}>
              {model.active ? 'Active' : 'Inactive'}
            </span>
          </div>
        </div>

        {/* Compact admin corner — only visible to admins. Plain text buttons,
            no overlays, since the F/B reference photos themselves are hidden
            on this page. Admin can still regenerate; the result becomes the
            new card image on /models. */}
        {isAdmin && (
          <div className="flex flex-wrap items-center gap-2 justify-end pt-1">
            <button
              onClick={handleRegenerateFront}
              disabled={regeneratingFront}
              className="border border-neutral-300 px-3 py-1.5 text-xs font-medium text-neutral-600 hover:bg-neutral-50 disabled:opacity-50 transition-colors"
              title="Regenerate the front reference image"
            >
              {regeneratingFront ? 'Regenerating…' : 'Regenerate Front'}
            </button>
            <button
              onClick={handleGenerateBack}
              disabled={generatingBack}
              className="border border-neutral-300 px-3 py-1.5 text-xs font-medium text-neutral-600 hover:bg-neutral-50 disabled:opacity-50 transition-colors"
              title="Generate (or regenerate) the back reference image"
            >
              {generatingBack ? 'Generating…' : (model.backReferenceImageUrl ? 'Regenerate Back' : 'Generate Back')}
            </button>
            <button
              onClick={() => {
                setShowCloneForm(!showCloneForm);
                if (!showCloneForm) {
                  const prefix = model.modelId.replace(/\d+$/, '');
                  const num = parseInt(model.modelId.replace(/\D+/g, '') || '0') + 1;
                  setCloneId(`${prefix}${num}`);
                  setCloneName(`${model.name} variant`);
                  setCloneDescription(model.description);
                  setCloneGender(model.gender);
                }
              }}
              className="border border-neutral-300 px-3 py-1.5 text-xs font-medium text-neutral-600 hover:bg-neutral-50 transition-colors"
            >
              Clone
            </button>
            {!confirmDelete ? (
              <button
                onClick={() => setConfirmDelete(true)}
                className="border border-red-200 px-3 py-1.5 text-xs font-medium text-red-500 hover:bg-red-50 transition-colors"
              >
                Delete
              </button>
            ) : (
              <span className="flex items-center gap-2">
                <button
                  onClick={handleDelete}
                  disabled={deleting}
                  className="bg-red-600 text-white px-3 py-1.5 text-xs font-medium hover:bg-red-700 disabled:opacity-30 transition-colors"
                >
                  {deleting ? 'Deleting…' : 'Confirm delete'}
                </button>
                <button
                  onClick={() => setConfirmDelete(false)}
                  className="border border-neutral-300 px-3 py-1.5 text-xs text-neutral-600 hover:bg-neutral-50"
                >
                  Cancel
                </button>
              </span>
            )}
          </div>
        )}
      </div>

      {/* 4K Model Asset Library — main visual content of this page.
          4 columns in a SINGLE ROW regardless of viewport, each square.
          Click any → fullscreen popup (image fills 100vw × 100vh).
          Generated via scripts/generate-model-assets.ts. */}
      {(model.assets4K_fullBodyFront ||
        model.assets4K_fullBodyBack ||
        model.assets4K_legsFront ||
        model.assets4K_legsBack) ? (
        <div className="mb-12">
          <div className="grid grid-cols-4 gap-4">
            {([
              ['Full body — front', model.assets4K_fullBodyFront],
              ['Full body — back',  model.assets4K_fullBodyBack],
              ['Legs — front (M01)', model.assets4K_legsFront],
              ['Legs — back (M02)',  model.assets4K_legsBack],
            ] as Array<[string, string | undefined]>).map(([label, url]) => (
              <div key={label} className="space-y-2">
                <div
                  className="aspect-square bg-neutral-100 border border-neutral-200 overflow-hidden relative cursor-zoom-in group"
                  onClick={() => url && setAssetLightbox(url)}
                >
                  {url ? (
                    <>
                      <img
                        src={url}
                        alt={label}
                        loading="lazy"
                        className="w-full h-full object-contain"
                      />
                      <div className="absolute inset-0 bg-black/0 group-hover:bg-black/15 transition-colors" />
                    </>
                  ) : (
                    <div className="w-full h-full flex items-center justify-center text-neutral-300 text-xs text-center px-3">
                      Not generated yet
                    </div>
                  )}
                </div>
                <p className="text-xs text-neutral-600 text-center">{label}</p>
              </div>
            ))}
          </div>
          {model.assets4K_updatedAt && (
            <p className="text-[10px] text-neutral-400 mt-2 text-right">
              4K assets updated {new Date(model.assets4K_updatedAt).toLocaleDateString()}
            </p>
          )}
        </div>
      ) : (
        <div className="border border-neutral-200 bg-neutral-50 p-6 mb-12 text-center">
          <p className="text-sm text-neutral-500">
            No 4K assets generated yet for this model.
          </p>
          <p className="text-xs text-neutral-400 mt-1">
            Run <code className="font-mono">npx tsx scripts/generate-model-assets.ts {model.modelId}</code> to create them.
          </p>
        </div>
      )}

      {/* Below the assets — celebrity check + description + create-job CTA */}
      <div className="max-w-3xl">
          {/* Celebrity Resemblance Audit */}
          {model.celebrityCheck ? (
            <div className={`mb-6 border px-4 py-3 ${
              model.celebrityCheck.status === 'pass' ? 'border-green-200 bg-green-50' :
              model.celebrityCheck.status === 'review' ? 'border-orange-200 bg-orange-50' :
              model.celebrityCheck.status === 'blocked' ? 'border-red-200 bg-red-50' :
              'border-neutral-200 bg-neutral-50'
            }`}>
              <div className="flex items-center gap-2 mb-1">
                <span className={`text-sm font-semibold ${
                  model.celebrityCheck.status === 'pass' ? 'text-green-700' :
                  model.celebrityCheck.status === 'review' ? 'text-orange-700' :
                  model.celebrityCheck.status === 'blocked' ? 'text-red-700' :
                  'text-neutral-600'
                }`}>
                  {model.celebrityCheck.status === 'pass' ? '\u2713 No celebrity resemblance' :
                   model.celebrityCheck.status === 'review' ? '\u26A0 Possible resemblance detected' :
                   model.celebrityCheck.status === 'blocked' ? '\u2717 Celebrity resemblance blocked' :
                   '\u26A0 Check error'}
                </span>
              </div>
              {model.celebrityCheck.topMatch && model.celebrityCheck.topScore !== undefined && (
                <p className="text-xs text-neutral-600 mb-1">
                  Closest match: <span className="font-medium">{model.celebrityCheck.topMatch}</span> ({(model.celebrityCheck.topScore * 100).toFixed(1)}% similarity)
                </p>
              )}
              {model.celebrityCheck.flaggedMatches && model.celebrityCheck.flaggedMatches.length > 1 && (
                <details className="text-xs text-neutral-500 mt-1">
                  <summary className="cursor-pointer hover:text-neutral-700">
                    {model.celebrityCheck.flaggedMatches.length} matches above threshold
                  </summary>
                  <ul className="mt-1 space-y-0.5 pl-3">
                    {model.celebrityCheck.flaggedMatches.map((m, i) => (
                      <li key={i}>{m.name} — {(m.score * 100).toFixed(1)}%</li>
                    ))}
                  </ul>
                </details>
              )}
              <p className="text-[10px] text-neutral-400 mt-2">
                {model.celebrityCheck.timestamp
                  ? new Date(
                      typeof model.celebrityCheck.timestamp === 'object' && '_seconds' in model.celebrityCheck.timestamp
                        ? model.celebrityCheck.timestamp._seconds * 1000
                        : model.celebrityCheck.timestamp
                    ).toLocaleString()
                  : ''} · {model.celebrityCheck.modelVersion} · DB {model.celebrityCheck.databaseVersion}
                {model.celebrityCheck.durationMs ? ` · ${model.celebrityCheck.durationMs}ms` : ''}
              </p>
              {model.celebrityCheck.note === 'no_face_detected' && (
                <p className="text-[10px] text-neutral-400">No face detected in reference image</p>
              )}
              {model.celebrityCheck.error && (
                <p className="text-[10px] text-red-400 mt-1">Error: {model.celebrityCheck.error}</p>
              )}
            </div>
          ) : (
            <div className="mb-6 border border-neutral-200 bg-neutral-50 px-4 py-3">
              <div className="flex items-center gap-2">
                <div className="w-3 h-3 border border-neutral-300 border-t-neutral-600 rounded-full animate-spin" />
                <span className="text-xs text-neutral-500">Celebrity resemblance check pending...</span>
              </div>
            </div>
          )}

          {/* Description */}
          <div className="mb-8">
            <h2 className="text-xs font-medium text-neutral-500 uppercase tracking-wider mb-2">Description</h2>
            <p className="text-sm text-neutral-700 whitespace-pre-wrap leading-relaxed">{model.description}</p>
          </div>

          {/* Primary action — Create Job. Clone and Delete now live in the
              admin corner at the top of the page (no duplicate buttons here). */}
          <div className="mb-8">
            <Link
              href={`/jobs/new?modelId=${model.modelId}`}
              className="block w-fit bg-neutral-900 text-white px-6 py-2.5 text-sm font-medium hover:bg-neutral-800 transition-colors"
            >
              Create Job with {model.modelId}
            </Link>
          </div>

          {/* Clone form */}
          {showCloneForm && (
            <div className="border border-neutral-200 bg-neutral-50 p-4 space-y-3">
              <p className="text-xs text-neutral-500">
                Create a new model using this one&apos;s reference photo. You can replace the photo later.
              </p>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-medium text-neutral-500 uppercase tracking-wider mb-1">New Model ID</label>
                  <input
                    type="text"
                    value={cloneId}
                    onChange={e => setCloneId(e.target.value.toUpperCase())}
                    placeholder="e.g., A4"
                    className="w-full border border-neutral-300 px-3 py-2 text-sm focus:outline-none focus:border-neutral-900"
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-neutral-500 uppercase tracking-wider mb-1">New Name</label>
                  <input
                    type="text"
                    value={cloneName}
                    onChange={e => setCloneName(e.target.value)}
                    placeholder="e.g., Red Berry v2"
                    className="w-full border border-neutral-300 px-3 py-2 text-sm focus:outline-none focus:border-neutral-900"
                  />
                </div>
              </div>

              <div>
                <label className="block text-xs font-medium text-neutral-500 uppercase tracking-wider mb-1">Gender</label>
                <div className="flex gap-2">
                  {(['female', 'male'] as const).map(g => (
                    <button
                      key={g}
                      onClick={() => setCloneGender(g)}
                      className={`px-3 py-1.5 text-xs font-medium transition-colors ${
                        cloneGender === g
                          ? 'bg-neutral-900 text-white'
                          : 'border border-neutral-300 text-neutral-600 hover:bg-neutral-50'
                      }`}
                    >
                      {g === 'female' ? 'Woman' : 'Man'}
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <label className="block text-xs font-medium text-neutral-500 uppercase tracking-wider mb-1">Description</label>
                <textarea
                  value={cloneDescription}
                  onChange={e => setCloneDescription(e.target.value)}
                  rows={4}
                  className="w-full border border-neutral-300 px-3 py-2 text-sm focus:outline-none focus:border-neutral-900 resize-none"
                />
              </div>

              <div className="flex gap-2">
                <button
                  onClick={handleClone}
                  disabled={!cloneId || !cloneName || cloning}
                  className="bg-neutral-900 text-white px-5 py-2 text-sm font-medium hover:bg-neutral-800 disabled:opacity-30 transition-colors"
                >
                  {cloning ? 'Saving...' : 'Save as New Model'}
                </button>
                <button
                  onClick={() => setShowCloneForm(false)}
                  className="border border-neutral-300 px-5 py-2 text-sm text-neutral-600 hover:bg-neutral-50 transition-colors"
                >
                  Cancel
                </button>
              </div>
              {error && error !== 'not_found' && (
                <p className="text-xs text-red-600">{error}</p>
              )}
            </div>
          )}
        </div>

      {/* 4K asset lightbox — first click on a thumb opens this (image fits the
          viewport at fit-window). Click backdrop or Esc closes the popup. */}
      {assetLightbox && (
        <div
          className="fixed inset-0 z-50 bg-black flex items-center justify-center cursor-zoom-out"
          onClick={() => setAssetLightbox(null)}
        >
          <img
            src={assetLightbox}
            alt="4K asset"
            className="max-w-screen max-h-screen w-screen h-screen object-contain"
          />
          <button
            onClick={() => setAssetLightbox(null)}
            className="absolute top-4 right-4 bg-white/15 hover:bg-white/30 text-white text-xs font-medium px-3 py-1.5 backdrop-blur-sm transition-colors"
          >
            Close (Esc)
          </button>
        </div>
      )}
    </Shell>
  );
}
