// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/jobs/[id]/results" | "/jobs/new" | "/models" | "/models/[id]" | "/models/new" | "/wardrobe"
type AppRouteHandlerRoutes = "/api/auth/[...nextauth]" | "/api/auth/otp" | "/api/generate" | "/api/jobs" | "/api/jobs/[id]" | "/api/models" | "/api/models/[id]" | "/api/models/generate-card" | "/api/qc" | "/api/seed" | "/api/shots/[id]/approve" | "/api/wardrobe"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/otp": {}
  "/api/generate": {}
  "/api/jobs": {}
  "/api/jobs/[id]": { "id": string; }
  "/api/models": {}
  "/api/models/[id]": { "id": string; }
  "/api/models/generate-card": {}
  "/api/qc": {}
  "/api/seed": {}
  "/api/shots/[id]/approve": { "id": string; }
  "/api/wardrobe": {}
  "/dashboard": {}
  "/jobs/[id]/results": { "id": string; }
  "/jobs/new": {}
  "/models": {}
  "/models/[id]": { "id": string; }
  "/models/new": {}
  "/wardrobe": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
