/**
 * Elbow-crop helper.
 *
 * M01 and M02 are no longer generated by Seedream. Instead they're produced by
 * cropping the full-body M03 (front) and M04 (back) tee-edited outputs to an
 * elbow-down 3:4 frame.
 *
 * Flow:
 *   1. Ask Gemini Flash Lite for the normalized y-coordinate (0 to 1) of the
 *      elbow line in the source full-body image.
 *   2. Sharp extracts from that y to the bottom (elbow-down).
 *   3. Centre-crop the width to 3:4 aspect.
 *
 * This guarantees M01 and M03 (and M02/M04) show the IDENTICAL garment, hem,
 * wash and pose — they are literally the same pixels.
 *
 * Why Gemini Flash Lite instead of a blind ratio: fit models and rendered
 * bodies vary, so a fixed "keep 70% from bottom" sometimes cuts chest, sometimes
 * cuts mid-stomach. A one-shot coordinate request handles the variance.
 */
import sharp from 'sharp';
import { analyzeWithFlashLite } from '@/lib/vertex';

/** If Gemini returns y outside this band, fall back to FALLBACK_Y. */
const Y_MIN = 0.25;
const Y_MAX = 0.55;
const FALLBACK_Y = 0.35;
const JPEG_QUALITY = 92;
const DOWNLOAD_TIMEOUT_MS = 30_000;

const ELBOW_PROMPT = `Look at this full-body studio photograph of a person standing.

Task: identify the horizontal line passing through the elbows (the elbow line).

Return ONLY a JSON object with the normalized vertical coordinate of that elbow line, where 0 is the very top of the image and 1 is the very bottom. No explanation, no other text.

Example output:
{"y": 0.38}

If the elbows are not visible (image does not contain a full-body person), return {"y": 0.35} as a default.`;

export interface ElbowCropResult {
  /** Cropped image buffer, JPEG. */
  imageData: Buffer;
  /** Always 'image/jpeg'. */
  mimeType: string;
  /** Width × height of the cropped output. */
  width: number;
  height: number;
  /** The y-coord actually used (useful for logging/debug). */
  yUsed: number;
  /** Whether Gemini's answer was used or the fallback kicked in. */
  fallbackApplied: boolean;
}

/**
 * Crop a full-body image to an elbow-down 3:4 frame.
 *
 * @param sourceUrl Publicly fetchable URL of the full-body source image.
 * @param apiKey    Optional Gemini API key override (falls back to GEMINI_API_KEY env).
 */
export async function cropElbowFromFullBody(
  sourceUrl: string,
  apiKey?: string,
): Promise<ElbowCropResult> {
  // 1. Download source
  console.log(`[ElbowCrop] Downloading source: ${sourceUrl.substring(0, 80)}...`);
  const resp = await fetch(sourceUrl, { signal: AbortSignal.timeout(DOWNLOAD_TIMEOUT_MS) });
  if (!resp.ok) throw new Error(`[ElbowCrop] Source fetch failed: ${resp.status}`);
  const sourceBuf = Buffer.from(await resp.arrayBuffer());
  const sourceMime = resp.headers.get('content-type') || 'image/png';

  // 2. Measure
  const metadata = await sharp(sourceBuf).metadata();
  const srcWidth = metadata.width!;
  const srcHeight = metadata.height!;
  console.log(`[ElbowCrop] Source ${srcWidth}×${srcHeight}`);

  // 3. Ask Gemini for elbow y-coordinate
  let yElbow = FALLBACK_Y;
  let fallbackApplied = false;
  try {
    const answer = await analyzeWithFlashLite({
      prompt: ELBOW_PROMPT,
      images: [{ buffer: sourceBuf, mimeType: sourceMime }],
      temperature: 0.1,
      apiKey,
    });

    // Parse — Gemini sometimes wraps in ```json ... ```
    const trimmed = answer.trim().replace(/^```(?:json)?\s*/, '').replace(/\s*```$/, '');
    const parsed = JSON.parse(trimmed) as { y?: number };
    if (typeof parsed.y === 'number' && parsed.y >= Y_MIN && parsed.y <= Y_MAX) {
      yElbow = parsed.y;
    } else {
      console.warn(`[ElbowCrop] Gemini returned y=${parsed.y}, outside [${Y_MIN}, ${Y_MAX}] — using fallback ${FALLBACK_Y}`);
      fallbackApplied = true;
    }
  } catch (err) {
    console.warn(`[ElbowCrop] Gemini call failed, using fallback y=${FALLBACK_Y}:`, err);
    fallbackApplied = true;
  }

  // 4. Crop elbow-down at 3:4 aspect
  const cropTop = Math.round(srcHeight * yElbow);
  const cropBottomHeight = srcHeight - cropTop;
  // 3:4 aspect → width = height * 3/4
  const targetWidth = Math.round(cropBottomHeight * 0.75);
  // Guard: if the required width is wider than the source, fall back to full width
  // and accept a non-3:4 aspect (very unlikely with our inputs).
  const finalWidth = Math.min(targetWidth, srcWidth);
  const cropLeft = Math.round((srcWidth - finalWidth) / 2);

  const croppedBuf = await sharp(sourceBuf)
    .extract({
      left: cropLeft,
      top: cropTop,
      width: finalWidth,
      height: cropBottomHeight,
    })
    .jpeg({ quality: JPEG_QUALITY, mozjpeg: true })
    .toBuffer();

  console.log(
    `[ElbowCrop] y=${yElbow.toFixed(3)}${fallbackApplied ? ' (fallback)' : ''} → ${finalWidth}×${cropBottomHeight}, ${(croppedBuf.length / 1024).toFixed(0)} KB`,
  );

  return {
    imageData: croppedBuf,
    mimeType: 'image/jpeg',
    width: finalWidth,
    height: cropBottomHeight,
    yUsed: yElbow,
    fallbackApplied,
  };
}
