/**
 * Crop helper for M01 / M02.
 *
 * M01 and M02 are no longer generated by Seedream. They're produced by cropping
 * the full-body M03 (front) and M04 (back) tee-edited outputs to a 3:4 frame.
 *
 * Two crop modes:
 *   - 'chin'  → top of crop at the chin/neck line. Produces a "jeans hero" frame
 *               (no head, full torso + legs + feet visible). Per slide 2 of the
 *               G-Star vault brief — the "Front jeans" / "Back jeans" framing.
 *   - 'elbow' → top of crop at the elbow line. Legacy framing (preserved for
 *               compatibility — not currently used by M01/M02 after rev 26+).
 *
 * Flow:
 *   1. Ask Gemini Flash Lite for the normalized y-coordinate (0 to 1) of the
 *      target line (chin or elbow) in the source full-body image.
 *   2. Sharp extracts from that y to the bottom.
 *   3. Centre-crop the width to 3:4 aspect.
 *
 * This guarantees M01 and M03 (and M02/M04) show the IDENTICAL garment, hem,
 * wash and pose — they are literally the same pixels.
 */
import sharp from 'sharp';
import { analyzeWithFlashLite } from '@/lib/vertex';

const JPEG_QUALITY = 92;
const DOWNLOAD_TIMEOUT_MS = 30_000;

export type CropMode = 'elbow' | 'chin' | 'chest' | 'waist' | 'upper-body';

interface CropPreset {
  prompt: string;
  yMin: number;
  yMax: number;
  fallback: number;
  label: string;
  /** Where to anchor the square crop within the source image.
   *  'bottom' (default) — feet stay at the parent's floor line. The square is
   *      taken from `[srcHeight - squareSide, srcHeight]`. Used for jeans-
   *      focus framings where the hem/footwear is the hero detail.
   *  'top' — head/shoulders stay at the parent's top edge. The square is
   *      taken from `[0, squareSide]`. Used for top-focus framings (e.g. a
   *      denim jacket as the hero) where the upper body must be the
   *      visible region — anchoring to the bottom would crop the focus
   *      garment out of frame entirely. */
  anchor?: 'bottom' | 'top';
}

const ELBOW_PROMPT = `Look at this full-body studio photograph of a person standing.

Task: identify the horizontal line passing through the elbows (the elbow line).

Return ONLY a JSON object with the normalized vertical coordinate of that elbow line, where 0 is the very top of the image and 1 is the very bottom. No explanation, no other text.

Example output:
{"y": 0.38}

If the elbows are not visible (image does not contain a full-body person), return {"y": 0.35} as a default.`;

const CHIN_PROMPT = `Look at this full-body studio photograph of a person standing.

Task: identify the horizontal line at the BOTTOM OF THE CHIN — i.e. the line where the head ends and the neck begins. The crop will START at this line and extend down to the feet, removing the head and face entirely while keeping the full torso and legs visible.

Return ONLY a JSON object with the normalized vertical coordinate of that chin line, where 0 is the very top of the image and 1 is the very bottom. No explanation, no other text.

Example output:
{"y": 0.18}

If the head is not visible or the image does not show a person, return {"y": 0.18} as a default.`;

const CHEST_PROMPT = `Look at this full-body studio photograph of a person standing with their arms hanging at their sides.

Task: identify the horizontal line at the BOTTOM OF THE COLLARBONE / TOP OF THE CHEST. This line passes through the upper torso just below the shoulders and through the upper arm at roughly the bicep level. The crop will START at this line and extend down to the feet — head, face, neck, and shoulders are entirely removed; what remains is the lower bicep, the chest/torso, the waist, the legs, and the feet.

Return ONLY a JSON object with the normalized vertical coordinate of that chest line, where 0 is the very top of the image and 1 is the very bottom. No explanation, no other text.

Example output:
{"y": 0.22}

If the chest line cannot be identified (image does not show a full-body person), return {"y": 0.22} as a default.`;

const WAIST_PROMPT = `Look at this full-body studio photograph of a person standing.

Task: identify the horizontal line JUST ABOVE the waistband / belt line of the pants — i.e. the line where the lower torso ends and the top edge of the pants begins, plus a small amount of body or top fabric visible above it. The crop will START at this line and extend down to the feet — head, shoulders, chest, and the upper torso are entirely removed; what remains is a small strip of body or top above the waistband, then the waistband itself, then the hips, legs, and feet.

Return ONLY a JSON object with the normalized vertical coordinate of that line, where 0 is the very top of the image and 1 is the very bottom. No explanation, no other text.

Example output:
{"y": 0.38}

If the waistband cannot be identified (image does not show a full-body person in pants), return {"y": 0.38} as a default.`;

const UPPER_BODY_PROMPT = `Look at this full-body studio photograph of a person standing.

Task: identify the horizontal line at the MID-FEMUR — i.e. the line halfway between the hip joint and the knee, roughly mid-thigh. The crop will END at this line and extend UPWARD to the top of the head, removing everything below mid-thigh while keeping the head, torso, hips, and the upper part of the thighs visible. The cropped frame is a top-anchored upper-body shot; the focus is the upper garment (jacket, shirt, top).

Return ONLY a JSON object with the normalized vertical coordinate of that mid-femur line, where 0 is the very top of the image and 1 is the very bottom. No explanation, no other text.

Example output:
{"y": 0.65}

If the mid-femur line cannot be identified (image does not show a full-body person), return {"y": 0.65} as a default.`;

const PRESETS: Record<CropMode, CropPreset> = {
  elbow:        { prompt: ELBOW_PROMPT,      yMin: 0.25, yMax: 0.55, fallback: 0.35, label: 'ElbowCrop'      },
  chin:         { prompt: CHIN_PROMPT,       yMin: 0.10, yMax: 0.30, fallback: 0.18, label: 'ChinCrop'       },
  chest:        { prompt: CHEST_PROMPT,      yMin: 0.15, yMax: 0.32, fallback: 0.22, label: 'ChestCrop'      },
  waist:        { prompt: WAIST_PROMPT,      yMin: 0.30, yMax: 0.48, fallback: 0.38, label: 'WaistCrop'      },
  'upper-body': { prompt: UPPER_BODY_PROMPT, yMin: 0.55, yMax: 0.78, fallback: 0.65, label: 'UpperBodyCrop', anchor: 'top' },
};

export interface ElbowCropResult {
  /** Cropped image buffer, JPEG. */
  imageData: Buffer;
  /** Always 'image/jpeg'. */
  mimeType: string;
  /** Width × height of the cropped output. */
  width: number;
  height: number;
  /** The y-coord actually used (useful for logging/debug). */
  yUsed: number;
  /** Whether Gemini's answer was used or the fallback kicked in. */
  fallbackApplied: boolean;
}

/**
 * Crop a full-body image to an elbow-down 3:4 frame.
 *
 * @param sourceUrl Publicly fetchable URL of the full-body source image.
 * @param apiKey    Optional Gemini API key override (falls back to GEMINI_API_KEY env).
 */
export async function cropFromFullBody(
  sourceUrl: string,
  mode: CropMode = 'chin',
  apiKey?: string,
): Promise<ElbowCropResult> {
  const preset = PRESETS[mode];
  // 1. Download source
  console.log(`[${preset.label}] Downloading source: ${sourceUrl.substring(0, 80)}...`);
  const resp = await fetch(sourceUrl, { signal: AbortSignal.timeout(DOWNLOAD_TIMEOUT_MS) });
  if (!resp.ok) throw new Error(`[${preset.label}] Source fetch failed: ${resp.status}`);
  const sourceBuf = Buffer.from(await resp.arrayBuffer());
  const sourceMime = resp.headers.get('content-type') || 'image/png';

  // 2. Measure
  const metadata = await sharp(sourceBuf).metadata();
  const srcWidth = metadata.width!;
  const srcHeight = metadata.height!;
  console.log(`[${preset.label}] Source ${srcWidth}×${srcHeight}`);

  // 3. Ask Gemini for the target y-coordinate
  let yTarget = preset.fallback;
  let fallbackApplied = false;
  try {
    const answer = await analyzeWithFlashLite({
      prompt: preset.prompt,
      images: [{ buffer: sourceBuf, mimeType: sourceMime }],
      temperature: 0.1,
      apiKey,
    });

    // Parse — Gemini sometimes wraps in ```json ... ```
    const trimmed = answer.trim().replace(/^```(?:json)?\s*/, '').replace(/\s*```$/, '');
    const parsed = JSON.parse(trimmed) as { y?: number };
    if (typeof parsed.y === 'number' && parsed.y >= preset.yMin && parsed.y <= preset.yMax) {
      yTarget = parsed.y;
    } else {
      console.warn(`[${preset.label}] Gemini returned y=${parsed.y}, outside [${preset.yMin}, ${preset.yMax}] — using fallback ${preset.fallback}`);
      fallbackApplied = true;
    }
  } catch (err) {
    console.warn(`[${preset.label}] Gemini call failed, using fallback y=${preset.fallback}:`, err);
    fallbackApplied = true;
  }

  const isTopAnchored = preset.anchor === 'top';

  // 3a. Lift the crop 5% higher so the frame shows more of the top above the
  //     pant waistband (matches the G-Star reference 3:4-style brand image).
  //     Applied only to BOTTOM-anchored crops — for top-anchored crops
  //     (upper-body), Gemini's mid-femur target is the intended bottom edge
  //     of the frame, and lifting it would shrink the visible body region.
  //     Floor-clamped at 0.05 so we never crop above the model's neckline.
  const HEADROOM_LIFT = 0.05;
  if (!isTopAnchored) {
    const yLifted = Math.max(0.05, yTarget - HEADROOM_LIFT);
    if (yLifted !== yTarget) {
      console.log(`[${preset.label}] yTarget ${yTarget.toFixed(3)} → ${yLifted.toFixed(3)} (lifted ${HEADROOM_LIFT * 100}%)`);
      yTarget = yLifted;
    }
  }

  // 4. Crop at 1:1 aspect (square — matches G-Star brand spec). Source is
  //    a 4000×4000 square M03/M04 anchor (post-Seedream + upscale). The
  //    crop math depends on the preset's `anchor` field:
  //      anchor = 'bottom' (waist / chest / chin / elbow): yTarget points
  //          to the TOP of the kept strip; the strip extends from yTarget
  //          to the bottom of the source. Square is taken from the BOTTOM
  //          of that strip so feet at the floor stay at the same y as the
  //          parent. (Used for jeans-focus crops — hem stays in frame.)
  //      anchor = 'top' (upper-body): yTarget points to the BOTTOM edge
  //          of the kept strip; the strip extends from y=0 (top of source)
  //          to yTarget. Square is taken from the TOP of that strip so the
  //          head stays at the same y as the parent. (Used for top-focus
  //          crops where the focus garment is the upper body.)
  let squareSide: number;
  let cropTopFinal: number;
  if (isTopAnchored) {
    const stripHeight = Math.round(srcHeight * yTarget);
    squareSide = Math.min(stripHeight, srcWidth);
    cropTopFinal = 0;
  } else {
    const cropTop = Math.round(srcHeight * yTarget);
    const cropBottomHeight = srcHeight - cropTop;
    squareSide = Math.min(cropBottomHeight, srcWidth);
    cropTopFinal = srcHeight - squareSide;
  }
  const cropLeft = Math.round((srcWidth - squareSide) / 2);

  const croppedBuf = await sharp(sourceBuf)
    .extract({
      left: cropLeft,
      top: cropTopFinal,
      width: squareSide,
      height: squareSide,
    })
    .jpeg({ quality: JPEG_QUALITY, mozjpeg: true })
    .toBuffer();
  const finalWidth = squareSide;
  const cropBottomHeightFinal = squareSide;

  console.log(
    `[${preset.label}] y=${yTarget.toFixed(3)}${fallbackApplied ? ' (fallback)' : ''} → ${finalWidth}×${cropBottomHeightFinal} (square), ${(croppedBuf.length / 1024).toFixed(0)} KB`,
  );

  return {
    imageData: croppedBuf,
    mimeType: 'image/jpeg',
    width: finalWidth,
    height: cropBottomHeightFinal,
    yUsed: yTarget,
    fallbackApplied,
  };
}

// Backwards-compat thin wrappers.
export const cropElbowFromFullBody = (sourceUrl: string, apiKey?: string) =>
  cropFromFullBody(sourceUrl, 'elbow', apiKey);
export const cropChinFromFullBody = (sourceUrl: string, apiKey?: string) =>
  cropFromFullBody(sourceUrl, 'chin', apiKey);
export const cropChestFromFullBody = (sourceUrl: string, apiKey?: string) =>
  cropFromFullBody(sourceUrl, 'chest', apiKey);
export const cropWaistFromFullBody = (sourceUrl: string, apiKey?: string) =>
  cropFromFullBody(sourceUrl, 'waist', apiKey);
export const cropUpperBodyFromFullBody = (sourceUrl: string, apiKey?: string) =>
  cropFromFullBody(sourceUrl, 'upper-body', apiKey);
