var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/models/generate-dressed-all/route.js")
R.c("server/chunks/[root-of-the-server]__df5d5854._.js")
R.c("server/chunks/node_modules_next_dist_9b6ee49a._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_7e8f41ca._.js")
R.c("server/chunks/node_modules_@google-cloud_firestore_build_src_a55966bf._.js")
R.c("server/chunks/node_modules_@google-cloud_firestore_build_protos_0dc0789e._.js")
R.c("server/chunks/node_modules_@google-cloud_firestore_package_json_6c8d5984._.js")
R.c("server/chunks/node_modules_protobufjs_c594357a._.js")
R.c("server/chunks/node_modules_google-gax_fb0deaea._.js")
R.c("server/chunks/b824c_google-auth-library_7ab28fa3._.js")
R.c("server/chunks/node_modules_@grpc_grpc-js_4855aa55._.js")
R.c("server/chunks/node_modules_665bca09._.js")
R.c("server/chunks/[root-of-the-server]__a5e0ee7e._.js")
R.c("server/chunks/_next-internal_server_app_api_models_generate-dressed-all_route_actions_b0eac60c.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/models/generate-dressed-all/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/models/generate-dressed-all/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
